const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
test('multi-keyword search automatically ranks all matches before partial matches',()=>{const a=load();a.run("state.stocks=[{symbol:'1101.TW',name:'甲',industry:'水泥',price:100},{symbol:'1102.TW',name:'乙',industry:'鋼鐵',price:200},{symbol:'1103.TW',name:'丙',industry:'水泥 鋼鐵',price:1},{symbol:'1104.TW',name:'丁',industry:'其他'}];state.search='水泥、鋼鐵';state.sort='priceDesc'");assert.equal(a.run('visibleStocks().map(s=>s.symbol).join()'),'1103.TW,1102.TW,1101.TW');a.run("state.search='水泥，鋼鐵'");assert.equal(a.run('visibleStocks().length'),3);assert.equal(a.run("queryGroups('silicon photonics').length"),1);assert.equal(a.run("queryGroups('矽光子 SiPh 矽光子').length"),1)});
test('balance ratios preserve zero, distinguish parent equity and use previous year end',()=>{const a=load();a.context.b={statements:[{date:'2026-06-30',assets:100,liabilities:40,current_assets:30,current_liabilities:20,cash:0,parent_equity:55},{date:'2025-12-31',parent_equity:50}]};assert.equal(a.run('balanceCalculations(b).debt'),.4);assert.equal(a.run('balanceCalculations(b).cash'),0);assert.equal(a.run('balanceCalculations(b).current'),1.5);assert.ok(Math.abs(a.run('balanceCalculations(b).equityChange')-.1)<1e-12);a.run('b.statements[0].current_liabilities=0');assert.equal(a.run('balanceCalculations(b).current'),null)});
test('company research stays compact and uses safe named modal launchers',()=>{const a=load();a.run('research.loading=false');const html=a.run("researchHtml({symbol:'2330.TW',name:'<台積電>'})");assert.match(html,/id="companyResearch"/);assert.match(html,/data-research-page="5"/);assert.match(html,/&lt;台積電&gt;/);assert.doesNotMatch(html,/<details>/);assert.match(a.run("metricPeriod('peg',{period_mode:'cagr5',date:'2025-Q4',comparison_period:'2020-Q4'})"),/2020 → 2025.*5 年複合/)});
function load(saved={}){const values=new Map(Object.entries(saved));const storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)};const elements=new Map();const element=()=>({textContent:'',innerHTML:'',className:'',value:'',hidden:false,disabled:false,querySelectorAll:()=>[],insertAdjacentHTML(){}});const context=vm.createContext({window:{localStorage:storage,addEventListener(){}},localStorage:storage,document:{getElementById:id=>{if(!elements.has(id))elements.set(id,element());return elements.get(id)},querySelectorAll:()=>[]},console,setTimeout,Date,URL,Blob});let src=fs.readFileSync(path.join(__dirname,'../site/app.js'),'utf8').replace(/init\(\);\s*$/,'');vm.runInContext(src,context);return {run:code=>vm.runInContext(code,context),values,context,elements}}
test('watchlist persists, cloud loading does not replace personal preferences',async()=>{const a=load();a.run("toggleWatch('2330.TW')");const b=load(Object.fromEntries(a.values));assert.equal(b.run("state.watchlist.join(',')"),'2330.TW');const fresh={schema_version:2,stocks:[],latest_price_date:null};b.context.fetch=async url=>({ok:true,json:async()=>url.includes('status')?{state:'ok'}:fresh});await b.run('fetchLive()');assert.equal(b.run("state.watchlist.join(',')"),'2330.TW');b.run("toggleWatch('2330.TW')");assert.equal(b.run('state.watchlist.length'),0);assert.equal(load().run('state.watchlist.length'),0)});
test('CSV handles BOM quoted fields, merges and ignores imported prices',()=>{const a=load();a.run('importWatchlist("\\ufeffsymbol,name,category,price\\n2330,\\\"A,B\\\",高成長股,999\\n2330.TW,duplicate,,888")');assert.equal(a.run('state.watchlist.length'),1);assert.equal(a.run("state.overrides['2330.TW']"),'高成長股');assert.equal(a.run('state.stocks.length'),0);assert.throws(()=>a.run('importWatchlist("symbol\\n<script>")'));assert.throws(()=>a.run('csvParse(\'"unclosed\')'))});
test('all original classification bands and gaps are retained',()=>{const a=load();for(const [cat,key,value,tone] of [['高成長股','peg',.4,'caution'],['高成長股','peg',.5,'positive'],['高成長股','peg',1,'neutral'],['高成長股','peg',1.5,'caution'],['高成長股','peg',2.01,'risk'],['重資產股','pb',.6,'risk'],['週期股','pb',.9,'positive'],['週期股','pb',3.1,'risk'],['虧損企業','ps',4,'positive'],['穩定獲利股','pe',10,'neutral']])assert.equal(a.run(`interpretation({category:${JSON.stringify(cat)},${key}:${value},gross_margin:70}).tone`),tone);assert.match(a.run("interpretation({category:'虧損企業',ps:4,gross_margin:40}).title"),/中間毛利/);assert.match(a.run("interpretation({category:'高成長股',peg:null}).title"),/無法判讀/);assert.match(a.run("interpretation({category:'高成長股',peg:.8,trailing_eps:-1}).title"),/不適用/)});
test('sorting handles nulls, range filters, category search and overrides',()=>{const a=load();a.run("state.stocks=[{symbol:'2330.TW',name:'A',category:'高成長股',price:null,peg:null},{symbol:'1101.TW',name:'B',category:'週期股',price:20,pb:.8}];state.sort='priceAsc'");assert.equal(a.run('visibleStocks()[0].symbol'),'1101.TW');a.run("state.priceMin=10;state.priceMax=30");assert.equal(a.run('visibleStocks().length'),1);a.run("state.priceMin=null;state.priceMax=null;state.search='高成長股'");assert.equal(a.run('visibleStocks().length'),1);a.run("state.overrides['2330.TW']='穩定獲利股'");assert.equal(a.run('visibleStocks().length'),0)});
test('failure, stale dates, empty data and unavailable storage are safe',()=>{const a=load();assert.match(a.run("freshness({}, {state:'failed'})"),/更新失敗/);assert.match(a.run("freshness({latest_price_date:'2026-09-01'},{state:'ok'},new Date('2026-10-01T11:00:00Z'))"),/過期/);assert.equal(a.run("freshness({latest_price_date:'2026-10-02'},{state:'ok'},new Date('2026-10-03T11:00:00Z'))"),'');assert.equal(a.run('readPreferences({getItem(){throw Error()}}).watchlist.length'),0);a.context.localStorage.setItem=()=>{throw Error('quota')};assert.equal(a.run('persist()'),false);assert.match(a.elements.get('notice').textContent,/無法儲存/)});
test('legacy cloud and manual lists never seed personal favorites',()=>{for(const mode of ['cloud','saved','manual']){const a=load({stock_lens_web_v1:JSON.stringify({mode,watchlist:['2330.TW','2881.TW'],overrides:{'2330.TW':{category:'穩定獲利股',fields:{price:999}}}})});assert.equal(a.run('state.watchlist.length'),0);assert.equal(a.run("state.overrides['2330.TW']"),'穩定獲利股');assert.equal(a.run('state.stocks.length'),0);a.run("toggleWatch('2330.TW')");assert.equal(load(Object.fromEntries(a.values)).run("state.watchlist.join(',')"),'2330.TW')}});
test('explicit v2 favorites and intentionally empty lists take precedence over legacy data',()=>{for(const favorites of [[],['2330.TW']]){const a=load({stock_lens_preferences_v2:JSON.stringify({watchlist:favorites,overrides:{'2330.TW':'高成長股'}}),stock_lens_web_v1:JSON.stringify({watchlist:['2881.TW']})});assert.equal(a.run("state.watchlist.join(',')"),favorites.join(','));assert.equal(a.run("state.overrides['2330.TW']"),'高成長股')}});

test('all valuation fields sort both directions, nulls stay last, watchlists share sorting',()=>{const a=load();a.run("state.stocks=[{symbol:'1101.TW',price:20,pe:2,pb:2,ps:2,peg:2},{symbol:'2330.TW',price:10,pe:1,pb:1,ps:1,peg:1},{symbol:'2881.TW',price:null,pe:null,pb:null,ps:null,peg:null}];state.watchlist=['1101.TW','2330.TW','2881.TW']");for(const tab of ['all','watchlist'])for(const field of ['price','pe','pb','ps','peg'])for(const direction of ['Asc','Desc']){a.run(`state.tab='${tab}';state.sort='${field}${direction}'`);assert.equal(a.run('visibleStocks()[0].symbol'),direction==='Asc'?'2330.TW':'1101.TW');assert.equal(a.run('visibleStocks()[2].symbol'),'2881.TW')}});

test('chart links target the selected TWSE stock and do not affect preferences',()=>{const a=load();assert.equal(a.run("tvUrl({symbol:'2330.TW'})"),'https://www.tradingview.com/chart/?symbol=TWSE%3A2330');a.run("state.stocks=[{symbol:'1101.TW',name:'台泥'}];state.selected='1101.TW';renderDetail()");assert.match(a.elements.get('detail').innerHTML,/TWSE%3A1101/);assert.match(a.elements.get('detail').innerHTML,/查看股價走勢/);assert.equal(a.run('state.watchlist.length'),0)});
test('research covers pending and reviewed companies with periods and stale notices',()=>{const a=load();const data={schema_version:1,profiles:JSON.parse(fs.readFileSync(path.join(__dirname,'../research/companies.json'),'utf8'))};for(const p of Object.values(data.profiles))p.status='researched';a.context.profileData=data;a.run('research.profiles=validateResearch(profileData);research.loading=false');assert.match(a.run("fullResearchHtml({symbol:'2330.TW'})"),/事業獲利另看部門損益/);assert.match(a.run("fullResearchHtml({symbol:'9999.TW'})"),/待查核/);assert.equal(a.run("researchAge({reviewed_at:'2026-10-02'},new Date('2026-10-16T00:00:00+08:00'))"),14);a.run("state.stocks=[{symbol:'2330.TW'},{symbol:'9999.TW'}];state.researchFilter='researched'");assert.equal(a.run('visibleStocks().length'),1);a.run("state.researchFilter='pending'");assert.equal(a.run('visibleStocks()[0].symbol'),'9999.TW')});
test('research rejects unsafe links and missing citations; failed loads retain prior research',async()=>{const a=load();const data={schema_version:1,profiles:JSON.parse(fs.readFileSync(path.join(__dirname,'../research/companies.json'),'utf8'))};for(const p of Object.values(data.profiles))p.status='researched';a.context.profileData=data;a.run('research.profiles=validateResearch(profileData)');data.profiles['2330.TW'].sources.annual.url='javascript:alert(1)';assert.throws(()=>a.run('validateResearch(profileData)'));data.profiles['2330.TW'].sources.annual.url='https://example.com';data.profiles['2330.TW'].business.text='<img src=x onerror=alert(1)>';assert.match(a.run("fullResearchHtml({symbol:'2330.TW'})"),/&lt;img/);a.context.fetch=async()=>{throw Error('offline')};await a.run('fetchResearch()');assert.equal(a.run('research.error'),true);assert.equal(a.run("research.profiles['2330.TW'].status"),'researched');assert.equal(a.run('state.watchlist.length'),0)});

test('workbook overview remains separate, escapes content and supports coverage filters',()=>{const a=load();const raw=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'../research/imported-overview.json.gz'))));const o=raw.profiles['1103.TW'];a.context.overviewData={schema_version:1,profiles:{'1103.TW':{status:'overview',limitations:[],sources:{},overview:o}}};a.run('research.profiles=validateResearch(overviewData);research.loading=false');assert.match(a.run("fullResearchHtml({symbol:'1103.TW'})"),/本次未重新逐一查閱原始網站/);assert.match(a.run("fullResearchHtml({symbol:'1103.TW'})"),/28\.50/);assert.doesNotMatch(a.run("fullResearchHtml({symbol:'1103.TW'})"),/最後查核：/);a.run("state.stocks=[{symbol:'1103.TW'},{symbol:'9999.TW'}];state.researchFilter='overview'");assert.equal(a.run('visibleStocks().length'),1);a.run("state.researchFilter='researched'");assert.equal(a.run('visibleStocks().length'),0);o.business='<script>alert(1)</script>';assert.match(a.run("fullResearchHtml({symbol:'1103.TW'})"),/&lt;script/);o.events=[{urls:['javascript:alert(1)']}];assert.throws(()=>a.run('validateResearch(overviewData)'))});

test('rolling finance explains revenue, EPS and dates without fixed quarter labels',()=>{const a=load();const raw=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'../research/imported-overview.json.gz'))));a.context.o=raw.profiles['2330.TW'];const html=a.run('overviewHtml(o)');assert.match(html,/淨利是扣除成本、費用與稅後的獲利/);assert.match(html,/TTM EPS/);assert.match(html,/2026 年 4–6 月/);assert.match(html,/每股盈餘（元）/);a.run("o.financial.rolling.period='2026-Q3';o.financial.rolling.quarters[3].period='2026-Q3'");assert.match(a.run('overviewHtml(o)'),/2026 年 7–9 月/)});

test('detail fills missing TTM EPS with dated workbook values and preserves official PE',()=>{const a=load();const raw=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'../research/imported-overview.json.gz'))));a.context.o=raw.profiles['2330.TW'];a.run("research.profiles={'2330.TW':{status:'overview',overview:o}};state.stocks=[{symbol:'2330.TW',name:'台積電',category:'穩定獲利股',pe:20,trailing_eps:null}];state.selected='2330.TW';renderDetail()");assert.match(a.run('companyMetricsHtml(state.stocks[0])'),/86\.28/);assert.match(a.run('companyMetricsHtml(state.stocks[0])'),/最近四季營收（億元）/);assert.match(a.elements.get('detail').innerHTML,/20\.00x/);assert.equal(a.run('state.stocks[0].trailing_eps'),null)});
test('outlook conclusions distinguish estimates, long-term targets, currency and missing data',()=>{const a=load();a.context.o={direction:'新產品',financial:{cumulative:{'2025-Q4':{basis:'合併營業收入',revenue:100}}}};a.context.x={type:'法人共識',period:'2026全年',scope:'合併營收',unit:'新台幣億元',low:120,high:null};assert.match(a.run('outlookConclusion(x,o)'),/增加約 20.00%/);assert.match(a.run('outlookConclusion(x,o)'),/研究機構預估/);a.run("x.unit='美元／億元'");assert.doesNotMatch(a.run('outlookConclusion(x,o)'),/與 2025 年/);a.run("x.type='公司長期目標（子公司）';x.scope='子公司';x.period='2030'");assert.match(a.run('outlookConclusion(x,o)'),/公司目標/);assert.match(a.run('outlookConclusion(x,o)'),/範圍：子公司/);a.run("x.type='待補查／無可用金額';x.low=null");assert.match(a.run('outlookConclusion(x,o)'),/未提供營收預估金額/)});
test('Chinese metric labels and periods distinguish cumulative EPS from trailing sales',()=>{const a=load();assert.equal(a.run("metricName('PE')"),'PE 本益比');assert.match(a.run("metricPeriod('eps',{date:'2026-Q2'})"),/2026 年截至第 2 季（1–6 月累計）/);assert.match(a.run("metricPeriod('ps',{date:'2026-Q2'})"),/2025 年 7 月–2026 年 6 月/);assert.match(a.run("metricPeriod('roe',{date:'2026-Q4'})"),/2026 年 1 月–2026 年 12 月/)});
test('derived PS fills main table, sorting and export materialization without replacing valid official fields',()=>{const a=load();a.run("research.profiles={'1234.TW':{overview:{source_filename:'test.xlsx',imported_at:'2026-10-04'},calculated_metrics:{ps:{value:2,period:'2026-Q2',formula:'公式'},calculated_pe:{value:20,period:'2026-Q2',formula:'公式'}}}};state.stocks=[{symbol:'1234.TW',category:'虧損企業',ps:null,pe:15},{symbol:'5678.TW',ps:3}];state.sort='psAsc'");assert.equal(a.run('visibleStocks()[0].ps'),2);assert.equal(a.run('visibleStocks()[0].pe'),15);assert.equal(a.run('state.stocks[0].ps'),null);assert.match(a.run('visibleStocks()[0].field_meta.ps.basis'),/匯入財報/)});

test('topic search covers plans, sourced notes, events and synonyms, without URL-only matches',()=>{const a=load();a.run("research.profiles={'1234.TW':{overview:{business:'半導體',direction:'正在發展 SiPh 平台',events:[{type:'進度',status:'已出貨',text:'Silicon Photonics 交付'}],outlooks:[]}},'5678.TW':{business:{text:'矽光子產品已量產'}},'9999.TW':{sources:{x:{url:'https://example.com/矽光子'}}}};state.stocks=[{symbol:'1234.TW',name:'甲'},{symbol:'5678.TW',name:'乙'},{symbol:'9999.TW',name:'丙'}];state.search='矽光子'");assert.equal(a.run('visibleStocks().length'),2);assert.match(a.run("keywordEvidence({symbol:'1234.TW'})"),/發展方向/);a.run("state.search='silicon photonics'");assert.equal(a.run('visibleStocks().length'),2);a.run("state.search='矽光子 甲'");assert.equal(a.run('visibleStocks().length'),2);assert.equal(a.run('visibleStocks()[0].symbol'),'1234.TW');assert.equal(a.run("hasSearchTerm('rail','ai')"),false);assert.equal(a.run("hasSearchTerm('ai伺服器','ai')"),true)});
test('overview layout separates business, performance and plans, and explains losses',()=>{const a=load();const raw=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'../research/imported-overview.json.gz'))));a.context.o=raw.profiles['1101.TW'];const html=a.run('overviewHtml(o)');assert.match(html,/① 這家公司做什麼/);assert.match(html,/② 最近一年的成績/);assert.match(html,/股東最後虧損多少/);assert.match(html,/④ 接下來往哪裡發展/);assert.match(a.run("plainResearchText('核准不等於完工')"),/已核准/)});
test('loss category migrates saved settings and old market snapshots without losing favorites',()=>{const a=load({stock_lens_preferences_v2:JSON.stringify({watchlist:['1234.TW'],overrides:{'1234.TW':'前期虧損企業'}})});assert.equal(a.run("state.overrides['1234.TW']"),'虧損企業');assert.equal(a.run('state.watchlist.length'),1);assert.equal(a.run("materialize({symbol:'5678.TW',category:'前期虧損企業'}).category"),'虧損企業')});
test('one search accepts topics, stock codes and combined keywords',()=>{const a=load();a.run("state.stocks=[{symbol:'1234.TW',name:'甲'},{symbol:'5678.TW',name:'乙'}];research.profiles={'1234.TW':{overview:{business:'矽光子',direction:'',outlooks:[],events:[]}},'5678.TW':{overview:{business:'矽光子',direction:'',outlooks:[],events:[]}}};state.search='矽光子'");assert.equal(a.run('visibleStocks().length'),2);a.run("state.search='矽光子 1234'");assert.equal(a.run('visibleStocks().length'),2);assert.equal(a.run('visibleStocks()[0].symbol'),'1234.TW');assert.match(a.run("keywordEvidence({symbol:'1234.TW'})"),/矽光子/)});
test('valuation guide highlights metric choice and separates classification from valuation',()=>{const a=load();a.run('renderRules()');const html=['pe','pb','ps','peg'].map(k=>a.elements.get('metric-rules-'+k).innerHTML).join('');assert.match(html,/適合哪些公司/);assert.match(html.replace(/<[^>]+>/g,''),/PB 股價淨值比＋ROE/);assert.match(html,/成長要用 EPS/);assert.match(html,/没有|沒有產品營收/);assert.match(html,/本站分類依據/);assert.match(html,/學習參考/)});

test('category filter moves its priority metric and matching values first',()=>{const a=load();for(const [category,metric] of [['週期股','pb'],['重資產股','pb'],['虧損企業','ps'],['高成長股','peg'],['穩定獲利股','pe']]){assert.equal(a.run(`metricColumnOrder('${category}')[0]`),metric);assert.equal(a.run(`new Set(metricColumnOrder('${category}')).size`),4);}assert.equal(a.run("metricColumnOrder('全部').join(',')"),'pe,pb,ps,peg');a.run("state.stocks=[{symbol:'1101.TW',name:'台泥',category:'週期股',pe:11,pb:2,ps:3,peg:4}];state.filter='週期股';render()");assert.ok(a.elements.get('stockHeaders').innerHTML.indexOf('>PB<')<a.elements.get('stockHeaders').innerHTML.indexOf('>PE<'));const row=a.elements.get('stockRows').innerHTML;assert.ok(row.indexOf('data-metric-help=\"pb\"')<row.indexOf('data-metric-help=\"pe\"'))});

test('PE peer range uses exact industry, matching official date and positive values',()=>{const a=load();a.run("state.stocks=[10,20,30,40,50].map((pe,i)=>({symbol:String(1101+i)+'.TW',industry:'水泥工業',pe,field_meta:{pe:{date:'2026-10-02'}}}));state.stocks.push({industry:'半導體業',pe:999,field_meta:{pe:{date:'2026-10-02'}}},{industry:'水泥工業',pe:999,field_meta:{pe:{date:'2026-10-01'}}},{industry:'水泥工業',pe:0,field_meta:{pe:{date:'2026-10-02'}}})");assert.equal(a.run('industryPeReference(state.stocks[0]).median'),30);assert.equal(a.run('industryPeReference(state.stocks[0]).low'),20);assert.equal(a.run('industryPeReference(state.stocks[0]).high'),40);assert.equal(a.run('industryPeReference(state.stocks[0]).count'),5);assert.equal(a.run('industryPeReference(state.stocks[0]).min'),10);assert.equal(a.run('industryPeReference(state.stocks[0]).max'),50);a.run('state.stocks.shift()');assert.equal(a.run('industryPeReference(state.stocks[0])'),null);assert.match(a.run("interpretation({category:'週期股',pb:0.8}).title"),/便宜？/);assert.match(a.run("interpretation({category:'週期股',pb:2}).title"),/貴？/)});

test('table metrics link to matching glossary entries without unsafe text',()=>{const a=load();assert.match(a.run("metricHelpLink('pb','PB 0.8x')"),/href="#glossary-pb"/);assert.match(a.run("metricHelpLink('pe','<script>')"),/&lt;script&gt;/);a.run("state.stocks=[{symbol:'1101.TW',name:'台泥',category:'週期股',pb:0.8}];render()");assert.match(a.elements.get('stockHeaders').innerHTML,/data-metric-help="pe"/);assert.match(a.elements.get('stockRows').innerHTML,/data-metric-help="pb"/);const html=fs.readFileSync(path.join(__dirname,'../site/index.html'),'utf8');for(const key of ['pe','pb','ps','peg'])assert.match(html,new RegExp('id="glossary-'+key+'"'))});

test('PE explanation distinguishes loss-company PS and large indicators link to definitions',()=>{const a=load();assert.match(a.run("industryPeDetailHtml({category:'虧損企業',industry:'食品工業'})"),/優先參考 PS/);assert.match(a.run("industryPeDetailHtml({category:'虧損企業'})"),/同類股票的 PE 區間，供你比較參考/);assert.match(a.run("linkedMetricPhrase('PB 股價淨值比＋ROE')"),/data-metric-help="pb"/);assert.match(a.run("linkedMetricPhrase('PB 股價淨值比＋ROE')"),/data-metric-help="roe"/);assert.equal(a.run("statHelpKey('trailing_eps')"),'eps')});

test('annual PEG keeps annual dates and formula while TTM PE stays separate',()=>{const a=load();a.context.annualProfile={overview:{source_filename:'提供資料'},calculated_metrics:{peg:{value:.8,period:'2025-Q4',comparison_period:'2024-Q4',period_mode:'annual',formula:'全年 EPS',price_date:'2026-10-02',eps_used:5,pe_used:20},earnings_growth:{value:25,period:'2025-Q4',comparison_period:'2024-Q4',period_mode:'annual'}}};a.run("research.profiles['2330.TW']=annualProfile");assert.equal(a.run("materialize({symbol:'2330.TW',peg:null}).peg"),.8);assert.match(a.run("metricPeriod('peg',materialize({symbol:'2330.TW'}).field_meta.peg)"),/2025 年全年 EPS（與 2024 年全年比較）/);assert.match(a.run("materialize({symbol:'2330.TW'}).peg_basis"),/2025 年全年/);a.run("annualProfile.calculated_metrics.peg.value=null;annualProfile.calculated_metrics.peg.reason='超出成長範圍'");assert.equal(a.run("materialize({symbol:'2330.TW',peg:null}).field_meta.peg.reason"),'超出成長範圍')});

test('priority category shows its own numeric metric and research wording keeps stages factual',()=>{const a=load();a.run("state.stocks=[{symbol:'1101.TW',name:'台泥',category:'週期股',pb:.82}];state.selected='1101.TW';render()");assert.match(a.elements.get('stockRows').innerHTML,/先看.*PB 0.82x/);assert.match(a.elements.get('detail').innerHTML,/先看.*0.82x/);assert.equal(a.run("plainResearchText('董事會通過增資；不等於新增營收5億元')"),'董事會通過增資；此 5 億元為子公司增資款');assert.match(a.run("plainResearchText('住宅已預售；預售不等同已交屋認列收入')"),/交屋與營收認列進度待確認/);assert.match(a.run("plainResearchText('公告不能視為已完成交割或全部營收已併入')"),/交割與營收併入時點待公告/)});
test('metric explanation has one canonical home in rules and a small quick popover',()=>{const html=fs.readFileSync(path.join(__dirname,'../site/index.html'),'utf8');const rules=html.slice(html.indexOf('<section id="rules"'),html.indexOf('<section id="sources"'));for(const key of ['pe','pb','ps','peg','roe','eps']){assert.match(rules,new RegExp('id="glossary-'+key+'"'));assert.equal(html.split('id="glossary-'+key+'"').length-1,1)}assert.match(html,/id="metricHelpPopover" popover="auto"/);assert.match(html,/查看完整估值說明/);const a=load();a.elements.set('glossary-pb',{querySelector:s=>({textContent:s==='dt'?'PB｜股價淨值比':'股價相對淨值的倍數'})});a.elements.set('metricHelpPopover',{showPopover(){this.shown=true}});a.run("state.tab='watchlist';state.page=3;openMetricHelp('pb')");assert.equal(a.run('state.tab'),'watchlist');assert.equal(a.run('state.page'),3);assert.equal(a.elements.get('metricHelpText').textContent,'股價相對淨值的倍數');assert.equal(a.elements.get('metricHelpPopover').shown,true)});

test('numeric metric hints explain PB direction and keep exact underlying value',()=>{const a=load();assert.match(a.run("metricValueExplanation('pb',.8)"),/股價低於/);assert.match(a.run("metricValueExplanation('pb',1.2)"),/股價高於/);assert.match(a.run("metricValueExplanation('pb',-1)"),/先確認/);assert.match(a.run("metricValueExplanation('pe',20)"),/20.00 元股價/);assert.match(a.run("metricValueExplanation('ps',2)"),/利潤率相近/);assert.match(a.run("metricHelpLink('pb','0.00x',.004)"),/data-metric-value="0.004"/)});

test('weekly change labels use five trading days and reject mismatched price dates',()=>{const a=load();a.run("movers.payload={periods:{'5':{start:'2026-09-23',end:'2026-10-02',changes:{'2330.TW':6.5,'1101.TW':-2}}}};");assert.match(a.run("weeklyChangeHtml({symbol:'2330.TW',price_date:'2026-10-02'})"),/近一週 \+6.5%/);assert.match(a.run("weeklyChangeHtml({symbol:'1101.TW',price_date:'2026-10-02'})"),/-2.0%/);assert.match(a.run("weeklyChangeHtml({symbol:'2330.TW',price_date:'2026-09-30'})"),/—/)});

test('company PE stays compact while peer distribution lives in a separate frame',()=>{const a=load();const html=a.run("industryPeHtml({symbol:'2330.TW',name:'台積電',pe:31.5})");assert.match(html,/PE 本益比：31.50 倍/);assert.match(html,/data-metric-value="31.5"/);assert.match(html,/同類企業本益比/);assert.doesNotMatch(html,/中間一半|PE 是常見/)});

test('search retry hint only appears when keyword results are empty',()=>{const a=load();a.run("state.stocks=[{symbol:'1101.TW',name:'台泥',category:'週期股'}];state.search='完全不存在的關鍵字';render()");assert.match(a.elements.get('stockRows').innerHTML,/empty-search-hint/);assert.match(a.elements.get('stockRows').innerHTML,/試試其他寫法，再搜尋一次看看～/);a.run("state.search='';state.filter='高成長股';render()");assert.doesNotMatch(a.elements.get('stockRows').innerHTML,/試試其他寫法/)});

test('priority glossary comes first and each category belongs to one metric',()=>{const html=fs.readFileSync(path.join(__dirname,'../site/index.html'),'utf8');const ids=[...html.matchAll(/class="glossary-item" id="glossary-([^"]+)"/g)].map(m=>m[1]);assert.deepEqual(ids.slice(0,5),['pe','pb','ps','peg','roe']);assert.doesNotMatch(html,/id="rulesGrid"/);const a=load();a.run('renderRules()');assert.match(a.elements.get('metric-rules-pb').innerHTML,/週期股/);assert.match(a.elements.get('metric-rules-pb').innerHTML,/重資產股/);assert.doesNotMatch(a.elements.get('metric-rules-pe').innerHTML,/重資產股/);assert.match(a.elements.get('metric-rules-peg').innerHTML,/高成長股/)});

test('company metrics are opened from research and removed from inline detail',()=>{const a=load();a.run("state.stocks=[{symbol:'1402.TW',name:'遠東新',category:'穩定獲利股',pe:14.53,field_meta:{pe:{date:'2026-10-02'}}}];state.selected='1402.TW';renderDetail()");assert.doesNotMatch(a.elements.get('detail').innerHTML,/class="stats-grid"|主要估值 ·/);const metrics=a.run('companyMetricsHtml(state.stocks[0])');assert.match(metrics,/14.53x/);assert.match(metrics,/2026\/10\/02/);assert.match(metrics,/各欄位來源、期間與缺值原因/);assert.equal(a.run("RESEARCH_PAGES[1][0]"),'metrics');assert.match(a.run('researchHtml(state.stocks[0])'),/metric-button-word/)});
