const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
function load(saved={}){const values=new Map(Object.entries(saved));const storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)};const elements=new Map();const element=()=>({textContent:'',innerHTML:'',className:'',value:'',hidden:false,disabled:false,querySelectorAll:()=>[],insertAdjacentHTML(){}});const context=vm.createContext({window:{localStorage:storage,addEventListener(){}},localStorage:storage,document:{getElementById:id=>{if(!elements.has(id))elements.set(id,element());return elements.get(id)},querySelectorAll:()=>[]},console,setTimeout,Date,URL,Blob});let src=fs.readFileSync(path.join(__dirname,'../site/app.js'),'utf8').replace(/init\(\);\s*$/,'');vm.runInContext(src,context);return {run:code=>vm.runInContext(code,context),values,context,elements}}
test('watchlist persists, cloud loading does not replace personal preferences',async()=>{const a=load();a.run("toggleWatch('2330.TW')");const b=load(Object.fromEntries(a.values));assert.equal(b.run("state.watchlist.join(',')"),'2330.TW');const fresh={schema_version:2,stocks:[],latest_price_date:null};b.context.fetch=async url=>({ok:true,json:async()=>url.includes('status')?{state:'ok'}:fresh});await b.run('fetchLive()');assert.equal(b.run("state.watchlist.join(',')"),'2330.TW');b.run("toggleWatch('2330.TW')");assert.equal(b.run('state.watchlist.length'),0);assert.equal(load().run('state.watchlist.length'),0)});
test('CSV handles BOM quoted fields, merges and ignores imported prices',()=>{const a=load();a.run('importWatchlist("\\ufeffsymbol,name,category,price\\n2330,\\\"A,B\\\",高成長股,999\\n2330.TW,duplicate,,888")');assert.equal(a.run('state.watchlist.length'),1);assert.equal(a.run("state.overrides['2330.TW']"),'高成長股');assert.equal(a.run('state.stocks.length'),0);assert.throws(()=>a.run('importWatchlist("symbol\\n<script>")'));assert.throws(()=>a.run('csvParse(\'"unclosed\')'))});
test('all original classification bands and gaps are retained',()=>{const a=load();for(const [cat,key,value,tone] of [['高成長股','peg',.4,'caution'],['高成長股','peg',.5,'positive'],['高成長股','peg',1,'neutral'],['高成長股','peg',1.5,'caution'],['高成長股','peg',2.01,'risk'],['重資產股','pb',.6,'risk'],['週期股','pb',.9,'positive'],['週期股','pb',3.1,'risk'],['前期虧損企業','ps',4,'positive'],['穩定獲利股','pe',10,'neutral']])assert.equal(a.run(`interpretation({category:${JSON.stringify(cat)},${key}:${value},gross_margin:70}).tone`),tone);assert.match(a.run("interpretation({category:'前期虧損企業',ps:4,gross_margin:40}).title"),/中間毛利/);assert.match(a.run("interpretation({category:'高成長股',peg:null}).title"),/無法判讀/);assert.match(a.run("interpretation({category:'高成長股',peg:.8,trailing_eps:-1}).title"),/不適用/)});
test('sorting handles nulls, range filters, category search and overrides',()=>{const a=load();a.run("state.stocks=[{symbol:'2330.TW',name:'A',category:'高成長股',price:null,peg:null},{symbol:'1101.TW',name:'B',category:'週期股',price:20,pb:.8}];state.sort='priceAsc'");assert.equal(a.run('visibleStocks()[0].symbol'),'1101.TW');a.run("state.priceMin=10;state.priceMax=30");assert.equal(a.run('visibleStocks().length'),1);a.run("state.priceMin=null;state.priceMax=null;state.search='高成長股'");assert.equal(a.run('visibleStocks().length'),1);a.run("state.overrides['2330.TW']='穩定獲利股'");assert.equal(a.run('visibleStocks().length'),0)});
test('failure, stale dates, empty data and unavailable storage are safe',()=>{const a=load();assert.match(a.run("freshness({}, {state:'failed'})"),/更新失敗/);assert.match(a.run("freshness({latest_price_date:'2026-09-01'},{state:'ok'},new Date('2026-10-01T11:00:00Z'))"),/過期/);assert.equal(a.run("freshness({latest_price_date:'2026-10-02'},{state:'ok'},new Date('2026-10-03T11:00:00Z'))"),'');assert.equal(a.run('readPreferences({getItem(){throw Error()}}).watchlist.length'),0);a.context.localStorage.setItem=()=>{throw Error('quota')};assert.equal(a.run('persist()'),false);assert.match(a.elements.get('notice').textContent,/無法儲存/)});
test('legacy cloud and manual lists never seed personal favorites',()=>{for(const mode of ['cloud','saved','manual']){const a=load({stock_lens_web_v1:JSON.stringify({mode,watchlist:['2330.TW','2881.TW'],overrides:{'2330.TW':{category:'穩定獲利股',fields:{price:999}}}})});assert.equal(a.run('state.watchlist.length'),0);assert.equal(a.run("state.overrides['2330.TW']"),'穩定獲利股');assert.equal(a.run('state.stocks.length'),0);a.run("toggleWatch('2330.TW')");assert.equal(load(Object.fromEntries(a.values)).run("state.watchlist.join(',')"),'2330.TW')}});
test('explicit v2 favorites and intentionally empty lists take precedence over legacy data',()=>{for(const favorites of [[],['2330.TW']]){const a=load({stock_lens_preferences_v2:JSON.stringify({watchlist:favorites,overrides:{'2330.TW':'高成長股'}}),stock_lens_web_v1:JSON.stringify({watchlist:['2881.TW']})});assert.equal(a.run("state.watchlist.join(',')"),favorites.join(','));assert.equal(a.run("state.overrides['2330.TW']"),'高成長股')}});

test('all valuation fields sort both directions, nulls stay last, watchlists share sorting',()=>{const a=load();a.run("state.stocks=[{symbol:'1101.TW',price:20,pe:2,pb:2,ps:2,peg:2},{symbol:'2330.TW',price:10,pe:1,pb:1,ps:1,peg:1},{symbol:'2881.TW',price:null,pe:null,pb:null,ps:null,peg:null}];state.watchlist=['1101.TW','2330.TW','2881.TW']");for(const tab of ['all','watchlist'])for(const field of ['price','pe','pb','ps','peg'])for(const direction of ['Asc','Desc']){a.run(`state.tab='${tab}';state.sort='${field}${direction}'`);assert.equal(a.run('visibleStocks()[0].symbol'),direction==='Asc'?'2330.TW':'1101.TW');assert.equal(a.run('visibleStocks()[2].symbol'),'2881.TW')}});

test('chart links target the selected TWSE stock and do not affect preferences',()=>{const a=load();assert.equal(a.run("tvUrl({symbol:'2330.TW'})"),'https://www.tradingview.com/chart/?symbol=TWSE%3A2330');a.run("state.stocks=[{symbol:'1101.TW',name:'台泥'}];state.selected='1101.TW';renderDetail()");assert.match(a.elements.get('detail').innerHTML,/TWSE%3A1101/);assert.match(a.elements.get('detail').innerHTML,/查看股價走勢/);assert.equal(a.run('state.watchlist.length'),0)});
test('research covers pending and reviewed companies with periods and stale notices',()=>{const a=load();const data={schema_version:1,profiles:JSON.parse(fs.readFileSync(path.join(__dirname,'../research/companies.json'),'utf8'))};for(const p of Object.values(data.profiles))p.status='researched';a.context.profileData=data;a.run('research.profiles=validateResearch(profileData);research.loading=false');assert.match(a.run("researchHtml({symbol:'2330.TW'})"),/營收占比不等於獲利占比/);assert.match(a.run("researchHtml({symbol:'9999.TW'})"),/待查核/);assert.equal(a.run("researchAge({reviewed_at:'2026-10-02'},new Date('2026-10-16T00:00:00+08:00'))"),14);a.run("state.stocks=[{symbol:'2330.TW'},{symbol:'9999.TW'}];state.researchFilter='researched'");assert.equal(a.run('visibleStocks().length'),1);a.run("state.researchFilter='pending'");assert.equal(a.run('visibleStocks()[0].symbol'),'9999.TW')});
test('research rejects unsafe links and missing citations; failed loads retain prior research',async()=>{const a=load();const data={schema_version:1,profiles:JSON.parse(fs.readFileSync(path.join(__dirname,'../research/companies.json'),'utf8'))};for(const p of Object.values(data.profiles))p.status='researched';a.context.profileData=data;a.run('research.profiles=validateResearch(profileData)');data.profiles['2330.TW'].sources.annual.url='javascript:alert(1)';assert.throws(()=>a.run('validateResearch(profileData)'));data.profiles['2330.TW'].sources.annual.url='https://example.com';data.profiles['2330.TW'].business.text='<img src=x onerror=alert(1)>';assert.match(a.run("researchHtml({symbol:'2330.TW'})"),/&lt;img/);a.context.fetch=async()=>{throw Error('offline')};await a.run('fetchResearch()');assert.equal(a.run('research.error'),true);assert.equal(a.run("research.profiles['2330.TW'].status"),'researched');assert.equal(a.run('state.watchlist.length'),0)});

test('workbook overview remains separate, escapes content and supports coverage filters',()=>{const a=load();const raw=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'../research/imported-overview.json.gz'))));const o=raw.profiles['1103.TW'];a.context.overviewData={schema_version:1,profiles:{'1103.TW':{status:'overview',limitations:[],sources:{},overview:o}}};a.run('research.profiles=validateResearch(overviewData);research.loading=false');assert.match(a.run("researchHtml({symbol:'1103.TW'})"),/本次未重新逐一查閱原始網站/);assert.match(a.run("researchHtml({symbol:'1103.TW'})"),/28\.50/);assert.doesNotMatch(a.run("researchHtml({symbol:'1103.TW'})"),/最後查核：/);a.run("state.stocks=[{symbol:'1103.TW'},{symbol:'9999.TW'}];state.researchFilter='overview'");assert.equal(a.run('visibleStocks().length'),1);a.run("state.researchFilter='researched'");assert.equal(a.run('visibleStocks().length'),0);o.business='<script>alert(1)</script>';assert.match(a.run("researchHtml({symbol:'1103.TW'})"),/&lt;script/);o.events=[{urls:['javascript:alert(1)']}];assert.throws(()=>a.run('validateResearch(overviewData)'))});

test('rolling finance explains revenue, EPS and dates without fixed quarter labels',()=>{const a=load();const raw=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'../research/imported-overview.json.gz'))));a.context.o=raw.profiles['2330.TW'];const html=a.run('overviewHtml(o)');assert.match(html,/營收不等於|不等於賺到的錢/);assert.match(html,/TTM EPS/);assert.match(html,/2026 年 4–6 月/);assert.match(html,/每股盈餘（元）/);a.run("o.financial.rolling.period='2026-Q3';o.financial.rolling.quarters[3].period='2026-Q3'");assert.match(a.run('overviewHtml(o)'),/2026 年 7–9 月/)});

test('detail fills missing TTM EPS with dated workbook values and preserves official PE',()=>{const a=load();const raw=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'../research/imported-overview.json.gz'))));a.context.o=raw.profiles['2330.TW'];a.run("research.profiles={'2330.TW':{status:'overview',overview:o}};state.stocks=[{symbol:'2330.TW',name:'台積電',category:'穩定獲利股',pe:20,trailing_eps:null}];state.selected='2330.TW';renderDetail()");assert.match(a.elements.get('detail').innerHTML,/86\.28/);assert.match(a.elements.get('detail').innerHTML,/最近四季營收（億元）/);assert.match(a.elements.get('detail').innerHTML,/20\.00x/);assert.equal(a.run('state.stocks[0].trailing_eps'),null)});
